### ISSUE TITLE
코드 제안

### ISSUE THREAD

**Issue by OSS3TEAM** [OSS3TEAM/OSS_3TEAM_Python_Project#6]
더 좋은 코드 제안하기!
~2022.11.20

**Comment by kanujoa** [comment]
오류 해결하기 위해 다음과 같은 코드 추가
import sys
input = sys.stdin.readline

**Comment by kanujoa** [comment]
1
2
3
4
5
6
7
8     --> 여기까지가 입력
8     --> 서로 다른 나머지 정상적으로 출력됨
